public class MyApexClass {
 public static void main(String[] args) {
        System.debug('MySampleClass deployed successfully!');
 System.debug('MySampleClass deployed successfully!');
 System.debug('MySampleClass deployed successfully!');
 System.debug('MySampleClass deployed successfully!');
 System.debug('MySampleClass deployed successfully!');
 System.debug('MySampleClass deployed successfully!');
 System.debug('MySampleClass deployed successfully!');
    }

}
